server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: ushan1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MicroServiceDemo1?createDatabaseIfNotExist=true